M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Mon 11 Aug 2025 06:09:32 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-11T18:09:32+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.1969
%
G90
G05
T1
X5.5571Y-7.1437
X5.9508Y-7.1437
X7.1516Y-7.1437
X7.5453Y-7.1437
M30
